<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyClaw.Core\MyClaw.Core.csproj" />
    <ProjectReference Include="..\MyClaw.Memory\MyClaw.Memory.csproj" />
    <ProjectReference Include="..\MyClaw.Skills\MyClaw.Skills.csproj" />
    <PackageReference Include="AgentScope.Core" Version="1.1.8" />
    <!-- <ProjectReference Include="..\..\..\agentscope.net\src\AgentScope.Core\AgentScope.Core.csproj" /> -->

  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
